= Generating Item and Building Icon Files

====
This docs page has yet to be written. Looking to help out? Feel free to contribute.
Contact us on the discord if you have any questions.
====

This page will eventually walk through using an Icon Generator tool to create icon images from the meshes of items and buildings.
Until then, look at the xref:CommunityResources/IconGenerator.adoc[list of community created tools]
and the tools' own documentation.

== Useful Mods for Icon Capture

You may also find the following mods useful in creating icons:

- https://ficsit.app/mod/ChromaKey[Chroma Key] - "Green screen" buildables in a variety of colors, including one that supports customizer painting
- https://ficsit.app/mod/Th3SMBuilder[Buildable Static Meshes] - Build any arbitrary static mesh as a standalone buildable

== Information from Coffee Stain Studios

// cspell:ignore Nathalie
Nathalie at Coffee Stain has shared a document containing information on how the base game's icons are created.
You can view said document
link:{attachmentsdir}/BeginnersGuide/generating_icons/Iconguide.pdf[here].
